/**
 * COCA / Oxford 3000 前段高频英文词表。存在即 "≤ cet4 / 日常词"，
 * 不进字典候选；不在列表里的词由 difficulty.ts 按音节 / 词长 / 领域继续打分。
 *
 * 覆盖 ~1500 词，对典型英文推文够用；需要更精细 Zipf 分布时替换为真实频率表。
 * 词表来源：COCA top-5000 节选 + Oxford 3000 A1-B2 核心词（公版合成）。
 */
export const COMMON_EN_WORDS: Set<string> = new Set<string>([
  // 顶层虚词 / 代词 / 助动词 (~100)
  'a', 'about', 'above', 'across', 'after', 'again', 'against', 'all', 'almost', 'alone',
  'along', 'already', 'also', 'although', 'always', 'am', 'among', 'an', 'and', 'another',
  'any', 'anyone', 'anything', 'anyway', 'anywhere', 'are', 'around', 'as', 'at', 'back',
  'be', 'because', 'been', 'before', 'behind', 'being', 'below', 'beside', 'between', 'beyond',
  'both', 'but', 'by', 'can', 'could', 'did', 'do', 'does', 'doing', 'done',
  'down', 'during', 'each', 'either', 'else', 'enough', 'even', 'ever', 'every', 'everyone',
  'everything', 'few', 'for', 'from', 'further', 'had', 'has', 'have', 'having', 'he',
  'her', 'here', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'however', 'i',
  'if', 'in', 'inside', 'into', 'is', 'it', 'its', 'itself', 'just', 'like',
  'many', 'may', 'me', 'might', 'mine', 'more', 'most', 'much', 'must', 'my',
  'myself', 'near', 'neither', 'never', 'next', 'no', 'none', 'nor', 'not', 'nothing',
  'now', 'of', 'off', 'often', 'on', 'once', 'one', 'only', 'or', 'other',
  'our', 'ours', 'ourselves', 'out', 'outside', 'over', 'own', 'same', 'she', 'should',
  'since', 'so', 'some', 'someone', 'something', 'sometimes', 'somewhere', 'soon', 'still', 'such',
  'than', 'that', 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these',
  'they', 'this', 'those', 'though', 'through', 'to', 'together', 'too', 'under', 'until',
  'up', 'upon', 'us', 'very', 'was', 'we', 'were', 'what', 'when', 'where',
  'whether', 'which', 'while', 'who', 'whom', 'whose', 'why', 'will', 'with', 'within',
  'without', 'would', 'yes', 'yet', 'you', 'your', 'yours', 'yourself', 'yourselves',

  // 高频动词 (~200)
  'accept', 'add', 'admit', 'affect', 'agree', 'allow', 'answer', 'appear', 'apply', 'arrive',
  'ask', 'attack', 'avoid', 'become', 'begin', 'believe', 'break', 'bring', 'build', 'buy',
  'call', 'care', 'carry', 'catch', 'cause', 'change', 'check', 'choose', 'claim', 'clean',
  'close', 'come', 'compare', 'complete', 'consider', 'contain', 'continue', 'cook', 'count', 'cover',
  'create', 'cross', 'cry', 'cut', 'deal', 'decide', 'deliver', 'depend', 'describe', 'develop',
  'die', 'discuss', 'divide', 'drink', 'drive', 'drop', 'eat', 'end', 'enjoy', 'enter',
  'exist', 'expect', 'explain', 'face', 'fall', 'fear', 'feel', 'fight', 'fill', 'find',
  'finish', 'fly', 'follow', 'forget', 'form', 'found', 'gave', 'gets', 'give', 'given',
  'go', 'going', 'got', 'grow', 'guess', 'hand', 'hang', 'happen', 'hate', 'head',
  'hear', 'heard', 'held', 'help', 'hit', 'hold', 'hope', 'hurt', 'imagine', 'include',
  'increase', 'involve', 'join', 'jump', 'keep', 'kept', 'kick', 'kill', 'knew', 'know',
  'known', 'laugh', 'lay', 'lead', 'learn', 'leave', 'led', 'left', 'let', 'lie',
  'like', 'listen', 'live', 'look', 'lose', 'lost', 'love', 'made', 'make', 'mark',
  'matter', 'mean', 'meant', 'meet', 'mention', 'miss', 'move', 'named', 'need', 'notice',
  'offer', 'open', 'order', 'pay', 'pick', 'place', 'plan', 'plant', 'play', 'point',
  'present', 'produce', 'prove', 'provide', 'pull', 'push', 'put', 'raise', 'reach', 'read',
  'realize', 'receive', 'remember', 'remain', 'report', 'require', 'result', 'return', 'rise', 'run',
  'said', 'save', 'saw', 'say', 'see', 'seek', 'seem', 'seen', 'sell', 'send',
  'serve', 'set', 'share', 'show', 'shown', 'sing', 'sit', 'sleep', 'smile', 'sold',
  'solve', 'sound', 'speak', 'spend', 'spoke', 'stand', 'start', 'stay', 'stop', 'study',
  'suggest', 'suppose', 'take', 'taken', 'talk', 'teach', 'tell', 'thank', 'think', 'thought',
  'throw', 'took', 'touch', 'travel', 'treat', 'try', 'turn', 'understand', 'use', 'used',
  'wait', 'walk', 'want', 'watch', 'wear', 'win', 'wish', 'wonder', 'work', 'worry',
  'write', 'wrote',

  // 高频名词（生活 / 时间 / 人 / 学习 ~300）
  'above', 'action', 'activity', 'address', 'age', 'air', 'answer', 'area', 'arm', 'art',
  'article', 'baby', 'back', 'bag', 'ball', 'bank', 'bar', 'base', 'bath', 'bathroom',
  'beach', 'bed', 'bedroom', 'beer', 'beginning', 'bill', 'bird', 'birthday', 'block', 'blood',
  'board', 'boat', 'body', 'bone', 'book', 'bottle', 'bottom', 'box', 'boy', 'bread',
  'break', 'bridge', 'brother', 'building', 'bus', 'business', 'button', 'cake', 'car', 'card',
  'care', 'case', 'cat', 'center', 'centre', 'century', 'chair', 'chance', 'change', 'chapter',
  'character', 'charge', 'check', 'child', 'children', 'choice', 'church', 'city', 'class', 'clock',
  'club', 'coat', 'coffee', 'cold', 'color', 'colour', 'company', 'computer', 'concept', 'concern',
  'condition', 'conference', 'contact', 'content', 'contract', 'control', 'corner', 'cost', 'country', 'couple',
  'course', 'court', 'cousin', 'cup', 'customer', 'dad', 'damage', 'dance', 'data', 'date',
  'daughter', 'day', 'death', 'decision', 'detail', 'difference', 'dinner', 'direction', 'director', 'doctor',
  'dog', 'door', 'drink', 'drive', 'duty', 'ear', 'earth', 'east', 'edge', 'education',
  'effect', 'effort', 'egg', 'election', 'end', 'energy', 'engine', 'environment', 'evening', 'event',
  'example', 'exercise', 'experience', 'eye', 'face', 'fact', 'factor', 'family', 'farm', 'father',
  'fear', 'feature', 'feeling', 'field', 'fight', 'figure', 'file', 'film', 'finger', 'fire',
  'fish', 'floor', 'food', 'foot', 'football', 'force', 'form', 'friend', 'front', 'fruit',
  'function', 'furniture', 'future', 'game', 'garden', 'gas', 'gate', 'girl', 'glass', 'goal',
  'government', 'grandfather', 'grandmother', 'ground', 'group', 'growth', 'hair', 'half', 'hand', 'head',
  'health', 'heart', 'heat', 'height', 'hero', 'history', 'hole', 'holiday', 'home', 'hope',
  'horse', 'hospital', 'hotel', 'hour', 'house', 'husband', 'idea', 'image', 'industry', 'information',
  'instance', 'interest', 'internet', 'island', 'issue', 'item', 'job', 'journey', 'key', 'kid',
  'kind', 'king', 'kitchen', 'knowledge', 'lady', 'lake', 'land', 'language', 'law', 'lawyer',
  'leader', 'leaf', 'length', 'letter', 'level', 'library', 'life', 'light', 'line', 'lip',
  'list', 'location', 'look', 'lot', 'love', 'machine', 'magazine', 'mail', 'majority', 'man',
  'manager', 'map', 'market', 'marriage', 'match', 'material', 'meal', 'meaning', 'meeting', 'member',
  'memory', 'message', 'method', 'middle', 'milk', 'mind', 'minute', 'mirror', 'miss', 'mistake',
  'model', 'moment', 'money', 'month', 'morning', 'mother', 'mountain', 'mouse', 'mouth', 'movie',
  'museum', 'music', 'name', 'nation', 'nature', 'neighbor', 'news', 'night', 'note', 'number',
  'object', 'ocean', 'office', 'officer', 'oil', 'operation', 'opinion', 'option', 'orange', 'order',
  'page', 'paint', 'painting', 'pair', 'paper', 'parent', 'park', 'part', 'party', 'passage',
  'past', 'path', 'patient', 'pay', 'peace', 'people', 'percent', 'person', 'phone', 'piano',
  'picture', 'piece', 'pizza', 'place', 'plan', 'plane', 'plant', 'plate', 'player', 'pocket',
  'point', 'police', 'policy', 'politics', 'pool', 'position', 'possibility', 'power', 'practice', 'presence',
  'president', 'pressure', 'price', 'problem', 'process', 'product', 'program', 'progress', 'project', 'property',
  'public', 'purpose', 'quality', 'question', 'race', 'radio', 'rain', 'range', 'rate', 'reaction',
  'reason', 'record', 'region', 'relation', 'relationship', 'report', 'research', 'response', 'rest', 'result',
  'review', 'right', 'ring', 'river', 'road', 'rock', 'role', 'room', 'row', 'rule',
  'sample', 'school', 'science', 'sea', 'season', 'seat', 'second', 'section', 'security', 'selection',
  'sense', 'service', 'set', 'shape', 'ship', 'shirt', 'shop', 'shoulder', 'side', 'sign',
  'significance', 'silver', 'sister', 'site', 'situation', 'size', 'sky', 'smoke', 'snow', 'society',
  'software', 'son', 'song', 'soul', 'sound', 'source', 'south', 'space', 'speech', 'speed',
  'spring', 'square', 'staff', 'stage', 'state', 'statement', 'station', 'step', 'stick', 'stone',
  'store', 'storm', 'story', 'stranger', 'street', 'string', 'structure', 'student', 'style', 'subject',
  'success', 'sugar', 'summer', 'sun', 'support', 'surface', 'system', 'table', 'task', 'teacher',
  'team', 'technology', 'teeth', 'telephone', 'television', 'temperature', 'term', 'test', 'text', 'theme',
  'theory', 'thing', 'thought', 'tie', 'time', 'today', 'tomorrow', 'tonight', 'tool', 'top',
  'topic', 'total', 'town', 'track', 'trade', 'train', 'tree', 'trip', 'trouble', 'truck',
  'truth', 'type', 'uncle', 'unit', 'university', 'user', 'valley', 'value', 'vehicle', 'version',
  'video', 'view', 'village', 'visit', 'voice', 'volume', 'wall', 'war', 'water', 'way',
  'weather', 'website', 'wedding', 'week', 'weekend', 'weight', 'west', 'wife', 'wind', 'window',
  'wine', 'winter', 'woman', 'women', 'wood', 'word', 'work', 'world', 'yard', 'year',
  'yesterday', 'youth',

  // 高频形容词 / 副词（~200）
  'able', 'active', 'actual', 'additional', 'afraid', 'alive', 'amazing', 'angry', 'annual', 'anxious',
  'available', 'average', 'aware', 'awful', 'bad', 'basic', 'beautiful', 'best', 'better', 'big',
  'black', 'blue', 'brief', 'bright', 'brown', 'busy', 'calm', 'careful', 'central', 'certain',
  'cheap', 'chief', 'civil', 'clean', 'clear', 'cold', 'comfortable', 'common', 'complete', 'complex',
  'confident', 'considerable', 'content', 'cool', 'correct', 'cultural', 'current', 'daily', 'dangerous', 'dark',
  'dead', 'dear', 'decent', 'deep', 'definite', 'different', 'difficult', 'direct', 'dirty', 'dry',
  'due', 'early', 'east', 'easy', 'economic', 'educational', 'effective', 'efficient', 'electric', 'empty',
  'equal', 'evil', 'exact', 'excellent', 'exciting', 'existing', 'expensive', 'extra', 'fair', 'false',
  'familiar', 'famous', 'fast', 'fat', 'favorite', 'federal', 'fewer', 'final', 'financial', 'fine',
  'firm', 'first', 'flat', 'foreign', 'former', 'free', 'fresh', 'friendly', 'full', 'fun',
  'general', 'glad', 'global', 'good', 'great', 'green', 'grey', 'happy', 'hard', 'healthy',
  'heavy', 'helpful', 'high', 'historical', 'honest', 'hot', 'huge', 'human', 'ill', 'important',
  'impossible', 'independent', 'industrial', 'initial', 'inner', 'intelligent', 'international', 'joint', 'junior', 'just',
  'kind', 'large', 'last', 'late', 'latter', 'leading', 'least', 'left', 'legal', 'less',
  'light', 'likely', 'limited', 'little', 'local', 'logical', 'lonely', 'long', 'loud', 'low',
  'lower', 'lucky', 'main', 'major', 'married', 'massive', 'medical', 'mental', 'middle', 'military',
  'minor', 'mixed', 'modern', 'narrow', 'national', 'natural', 'nearby', 'necessary', 'negative', 'nervous',
  'new', 'nice', 'normal', 'northern', 'obvious', 'odd', 'official', 'ok', 'old', 'open',
  'original', 'other', 'overall', 'particular', 'past', 'perfect', 'permanent', 'personal', 'physical', 'pink',
  'plain', 'pleasant', 'political', 'poor', 'popular', 'positive', 'possible', 'powerful', 'practical', 'present',
  'pretty', 'previous', 'primary', 'principal', 'private', 'probable', 'professional', 'proper', 'public', 'purple',
  'pure', 'quick', 'quiet', 'rare', 'raw', 'ready', 'real', 'recent', 'red', 'regional',
  'regular', 'relevant', 'remote', 'responsible', 'rich', 'right', 'rough', 'round', 'royal', 'rural',
  'sad', 'safe', 'scientific', 'secondary', 'secret', 'secure', 'senior', 'separate', 'serious', 'several',
  'sharp', 'short', 'sick', 'silent', 'similar', 'simple', 'single', 'slight', 'slow', 'small',
  'smart', 'smooth', 'soft', 'solid', 'southern', 'special', 'specific', 'spiritual', 'standard', 'steady',
  'strange', 'strong', 'stupid', 'successful', 'sudden', 'sufficient', 'sure', 'sweet', 'tall', 'thick',
  'thin', 'tight', 'tiny', 'tired', 'total', 'tough', 'traditional', 'true', 'typical', 'ugly',
  'uncommon', 'unfair', 'unhappy', 'unique', 'united', 'unknown', 'unusual', 'upper', 'urgent', 'useful',
  'usual', 'various', 'vast', 'violent', 'warm', 'weak', 'weekly', 'welcome', 'western', 'wet',
  'white', 'whole', 'wide', 'wild', 'willing', 'wise', 'wonderful', 'wooden', 'worried', 'wrong',
  'yellow', 'young',

  // 高频副词补 (~80)
  'abroad', 'actually', 'ahead', 'aside', 'awake', 'away', 'certainly', 'clearly', 'commonly', 'completely',
  'deeply', 'definitely', 'directly', 'early', 'easily', 'especially', 'essentially', 'eventually', 'exactly', 'extremely',
  'fairly', 'finally', 'fortunately', 'frequently', 'fully', 'generally', 'hardly', 'highly', 'immediately', 'importantly',
  'increasingly', 'indeed', 'instead', 'late', 'literally', 'mainly', 'mostly', 'naturally', 'nearly', 'normally',
  'obviously', 'occasionally', 'originally', 'particularly', 'partly', 'perfectly', 'perhaps', 'personally', 'physically', 'possibly',
  'previously', 'probably', 'quickly', 'quietly', 'quite', 'rapidly', 'rarely', 'rather', 'really', 'recently',
  'regularly', 'relatively', 'seriously', 'shortly', 'significantly', 'similarly', 'slowly', 'somehow', 'strongly', 'suddenly',
  'surely', 'surprisingly', 'totally', 'truly', 'typically', 'ultimately', 'usually', 'virtually', 'widely', 'wholly',

  // 科技 / 互联网 / 职场常用 (~150)
  'account', 'action', 'active', 'app', 'application', 'attached', 'backup', 'blog', 'browser', 'bug',
  'button', 'cache', 'case', 'channel', 'chat', 'click', 'client', 'close', 'cloud', 'code',
  'command', 'comment', 'company', 'config', 'content', 'copy', 'create', 'data', 'database', 'design',
  'device', 'digital', 'disk', 'display', 'domain', 'download', 'drive', 'edit', 'email', 'enter',
  'error', 'event', 'export', 'feed', 'feedback', 'file', 'filter', 'folder', 'form', 'format',
  'function', 'graphic', 'hack', 'hardware', 'header', 'host', 'html', 'icon', 'image', 'import',
  'input', 'install', 'interface', 'internet', 'ios', 'java', 'json', 'keyboard', 'label', 'launch',
  'layer', 'layout', 'library', 'license', 'link', 'linux', 'list', 'load', 'local', 'log',
  'login', 'mac', 'map', 'menu', 'message', 'method', 'mobile', 'mode', 'module', 'monitor',
  'mouse', 'network', 'node', 'notice', 'object', 'online', 'open', 'operator', 'option', 'order',
  'output', 'package', 'page', 'panel', 'parameter', 'password', 'path', 'pattern', 'performance', 'phone',
  'photo', 'picture', 'pixel', 'platform', 'plugin', 'post', 'preview', 'print', 'process', 'product',
  'profile', 'program', 'project', 'prompt', 'protocol', 'query', 'queue', 'quick', 'random', 'range',
  'record', 'release', 'remove', 'report', 'request', 'response', 'restore', 'result', 'right', 'route',
  'save', 'screen', 'search', 'section', 'server', 'service', 'session', 'setting', 'setup', 'shortcut',
  'site', 'software', 'source', 'space', 'speed', 'stack', 'standard', 'status', 'stream', 'string',
  'style', 'sync', 'table', 'tag', 'target', 'template', 'text', 'theme', 'thread', 'time',
  'title', 'token', 'tool', 'trace', 'track', 'transfer', 'type', 'undo', 'update', 'upload',
  'url', 'user', 'value', 'variable', 'version', 'video', 'view', 'volume', 'web', 'website',
  'window', 'wireless', 'workspace', 'zone',

  // 日常动词 / 状态动词补 (~80)
  'act', 'adapt', 'advance', 'approve', 'arrange', 'argue', 'arrive', 'attend', 'behave', 'belong',
  'benefit', 'blame', 'borrow', 'burn', 'challenge', 'charge', 'chase', 'collect', 'combine', 'comment',
  'compete', 'concern', 'confirm', 'connect', 'control', 'convert', 'copy', 'correct', 'count', 'crash',
  'cure', 'deliver', 'demand', 'deny', 'deserve', 'design', 'desire', 'destroy', 'direct', 'disagree',
  'discover', 'display', 'dream', 'dress', 'drop', 'earn', 'escape', 'estimate', 'exchange', 'exist',
  'expand', 'expect', 'extend', 'fail', 'fix', 'forbid', 'gain', 'gather', 'generate', 'handle',
  'identify', 'improve', 'indicate', 'influence', 'inform', 'insist', 'intend', 'introduce', 'invest', 'invite',
  'judge', 'launch', 'lock', 'maintain', 'manage', 'matter', 'mention', 'obtain', 'occur', 'offer',
  'operate', 'organize', 'participate', 'perform', 'permit', 'persuade', 'possess', 'predict', 'prefer', 'prepare',
  'prevent', 'promote', 'promise', 'protect', 'provide', 'publish', 'realize', 'recognize', 'recommend', 'reduce',
  'refer', 'reflect', 'refuse', 'regard', 'register', 'regret', 'reject', 'relate', 'release', 'remove',
  'repair', 'replace', 'represent', 'request', 'respond', 'reveal', 'risk', 'search', 'select', 'settle',
  'shake', 'shine', 'shoot', 'shout', 'stretch', 'struggle', 'succeed', 'suffer', 'supply', 'survive',
  'swim', 'switch', 'throw', 'treat', 'trust', 'update', 'waste', 'wave', 'wonder', 'yield',

  // 不规则动词过去式 / 分词（stemmer 屈折回退抓不到这些形态，必须直列）—— 都是 cet4 级
  'ate', 'beat', 'became', 'began', 'begun', 'bent', 'bit', 'blew', 'blown', 'bore',
  'born', 'bought', 'broke', 'broken', 'brought', 'built', 'burnt', 'bust', 'came', 'caught',
  'chose', 'chosen', 'crept', 'cut', 'dealt', 'dove', 'drew', 'drawn', 'drove', 'driven',
  'eaten', 'fell', 'fallen', 'fed', 'felt', 'fled', 'flew', 'flown', 'forbade', 'forbidden',
  'forgot', 'forgotten', 'froze', 'frozen', 'gave', 'given', 'goes', 'gone', 'grew', 'grown',
  'hid', 'hidden', 'hit', 'hits', 'hurt', 'kept', 'knew', 'known', 'laid', 'lain',
  'led', 'left', 'lent', 'lit', 'lost', 'made', 'meant', 'met', 'paid', 'quit',
  'ran', 'rang', 'rose', 'risen', 'rode', 'ridden', 'said', 'sat', 'saw', 'seen',
  'sent', 'set', 'shaken', 'shone', 'shook', 'shot', 'shown', 'shut', 'sang', 'sunk',
  'sunk', 'slept', 'slid', 'sold', 'sowed', 'spoke', 'spoken', 'spent', 'split', 'spread',
  'stole', 'stolen', 'stood', 'struck', 'sung', 'swept', 'swore', 'sworn', 'swum', 'taken',
  'taught', 'told', 'thought', 'threw', 'thrown', 'told', 'understood', 'woke', 'woken', 'won',
  'wore', 'worn', 'wrote', 'written',

  // 高频但之前漏了的词（基础动词 / 情态 / 小名词）
  'get', 'gets', 'hey', 'hi', 'lot', 'lots', 'sir', 'mr', 'mrs', 'dr',
  'pm', 'am', 'app', 'apps', 'ai', 'api', 'tv', 'pc', 'ok', 'okay',
  'yeah', 'nope', 'yep', 'wow', 'cool', 'nice', 'haha', 'lol', 'btw', 'tbh',
  'pass', 'passed', 'passing', 'pick', 'picked', 'reach', 'reached', 'start', 'started', 'stopped',
  'stay', 'stayed', 'stays', 'try', 'tried', 'trying', 'tries', 'turn', 'turned', 'turning',
  'walk', 'walked', 'walking', 'work', 'worked', 'working', 'works', 'want', 'wanted', 'wanting',
  'look', 'looked', 'looking', 'looks', 'make', 'makes', 'making', 'made', 'take', 'takes',
  'taking', 'came', 'comes', 'coming', 'goes', 'going', 'gone', 'leave', 'leaves', 'leaving',
  'like', 'likes', 'liking', 'liked', 'love', 'loves', 'loved', 'loving', 'live', 'lives',
  'living', 'lived', 'hope', 'hoped', 'hoping', 'hopes', 'need', 'needs', 'needed', 'needing',
  'play', 'played', 'playing', 'plays', 'feel', 'feels', 'felt', 'feeling', 'keep', 'keeps',
  'keeping', 'kept', 'find', 'finds', 'found', 'finding', 'move', 'moves', 'moved', 'moving',
  'join', 'joined', 'joining', 'visit', 'visited', 'build', 'builds', 'built', 'building',

  // X / 科技圈高频
  'post', 'posts', 'posted', 'reply', 'replies', 'replied', 'retweet', 'retweeted', 'quote', 'quoted',
  'tweet', 'tweets', 'tweeted', 'like', 'liked', 'follow', 'followed', 'follower', 'followers', 'following',
  'unfollow', 'mention', 'mentioned', 'dm', 'trend', 'trending', 'hashtag', 'thread', 'threads', 'fyp',
  'stream', 'streamed', 'streaming', 'subscribe', 'subscribed', 'subscriber', 'share', 'shared', 'sharing', 'click',
  'clicked', 'scroll', 'scrolled', 'scrolling', 'launch', 'launched', 'launching',

  // 日常形容词 / 副词 补漏
  'extra', 'huge', 'super', 'actual', 'angry', 'bored', 'mad', 'cute', 'tired', 'busy',
  'funny', 'lucky', 'wild', 'weird', 'crazy', 'fine', 'nice', 'tough', 'cheap', 'proud',
  'alone', 'amazing', 'broken', 'empty', 'tiny', 'safe', 'lame', 'real', 'ready', 'pretty',
  'sick', 'soft', 'tight', 'tall', 'thick', 'quick', 'slow', 'open', 'close', 'dark',
  'dim', 'clear', 'clean', 'dirty', 'sharp', 'heavy', 'light',
]);
